apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  type: NodePort
  ports:
  - port: 1883
    nodePort: 30002
    protocol: TCP
    name: mqtt1
  - port: 9001
    nodePort: 30003
    protocol: TCP
    name: mqtt2
  selector:
    app: mqtt-broker
