apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  type: NodePort
  selector:
    app: ai-service
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30005
