apiVersion: v1
kind: Service
metadata:
  name: nodered-svc
  labels:
    app: nodered
spec:
  type: NodePort
  ports:
  - port: 1880
    nodePort: 30001
    protocol: TCP
    name: nr-bwsr
  selector:
    app: nodered
